version: '2'
services:
  jenkins:
    image: registry.hub.docker.com/bitnami/jenkins:2.346.1-debian-11-r0
    ports:
      - '8080:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
volumes:
  jenkins_data:
    driver: local
