version: "3.9"
services:
  jenkins: 
    image: registry.hub.docker.com/jenkins/jenkins:2.358-jdk11
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - "./jenkins_home:/var/jenkins_home"

